[package]
name = "ton-kafka-producer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
async-trait = "0.1"
base64 = "0.13"
chrono = "0.4"
config = { version = "0.12", default-features = false, features = ["yaml"] }
countme = { version = "3.0.0", features = ["enable"] }
futures = "0.3"
hex = "0.4"
http = "0.2.6"
indicatif = "0.17.0-rc.9"
log = "0.4"
log4rs = "1.0"
once_cell = "1.10.0"
parking_lot = "0.12.0"
pomfrit = "0.1"
public-ip = "0.2"
rand = "0.8"
rdkafka = { version = "0.28.0", features = ["sasl", "ssl-vendored", "tokio"] }
regex = "1.5.4"
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tokio = { version = "1.17.0", features = ["full", "parking_lot"] }
axum = "0.5.4"
axum-jrpc = "0.1"

# TON specific dependencies
ton_block = { git = "https://github.com/broxus/ton-labs-block" }
ton_block_json = { git = "https://github.com/broxus/ton-labs-block-json" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }
ton-block-compressor = { git = "https://github.com/broxus/ton-block-compressor" }

tiny-adnl = { git = "https://github.com/broxus/tiny-adnl" }

nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = false }
nekoton-utils = { git = "https://github.com/broxus/nekoton.git", default-features = false }
nekoton-indexer-utils = { git = "https://github.com/broxus/nekoton.git", default-features = false }

ton-indexer = { git = "https://github.com/broxus/ton-indexer.git" }

[dev-dependencies]
cargo-husky = { version = "1", features = ["run-cargo-clippy", "run-cargo-fmt"] }
